services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
    volumes:
      - /home/pi/aplicaciones/configuracion/sonarr:/config
      - /media/pi/Hector/Videos/Series:/tv:rw
      - /media/pi/Hector/descargas:/downloads:ro
    ports:
      - 8989:8989
    restart: unless-stopped
